/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      // Exact hex codes from neuralscreen (LogScreen.html) — source of truth
      colors: {
        "on-tertiary-fixed-variant": "#095300",
        "secondary-container": "#fe00fe",
        "secondary": "#ffabf3",
        "surface-container-lowest": "#0e0e10",
        "tertiary": "#e8ffda",
        "surface-dim": "#131315",
        "surface-variant": "#353437",
        "on-background": "#e5e1e4",
        "tertiary-fixed-dim": "#2ae500",
        "on-surface-variant": "#b9cacb",
        "outline-variant": "#3a494b",
        "surface": "#131315",
        "on-tertiary": "#053900",
        "primary-fixed": "#00f3ff",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed-dim": "#fe00fe",
        "outline": "#849495",
        "surface-tint": "#00f3ff",
        "on-tertiary-fixed": "#022100",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#500050",
        "primary-fixed-dim": "#00dce6",
        "primary-container": "#00f3ff",
        "surface-bright": "#39393b",
        "on-error": "#690005",
        "on-secondary": "#5b005b",
        "on-primary": "#00373a",
        "inverse-surface": "#e5e1e4",
        "surface-container-low": "#1c1b1d",
        "background": "#0e0e10",
        "on-secondary-fixed": "#380038",
        "on-primary-container": "#006b71",
        "secondary-fixed": "#ffd7f5",
        "primary": "#00f3ff",
        "on-primary-fixed": "#002022",
        "tertiary-container": "#36fd0f",
        "tertiary-fixed": "#79ff5b",
        "on-secondary-fixed-variant": "#810081",
        "on-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        "surface-container-highest": "#353437",
        "on-tertiary-container": "#107000",
        "inverse-primary": "#00696f",
        "surface-container": "#201f21",
        "on-primary-fixed-variant": "#004f53",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        kode: ["KodeMono_400Regular"],
        "kode-bold": ["KodeMono_700Bold"],
        mono: ["KodeMono_400Regular"],
      },
    },
  },
};
